CREATE OR REPLACE TABLE CICD_DEV_DB.CORE.CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
-- trigger deploy
-- trigger deploy again
