name: Deploy DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_DEV }}
      SNOWFLAKE_ROLE: CICD_ROLE
      SNOWFLAKE_WAREHOUSE: CICD_WH
      SNOWFLAKE_DATABASE: CICD_DEV_DB
      SNOWFLAKE_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW_DEV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@main

      - name: Write private key
        run: |
          echo "$SNOWFLAKE_PRIVATE_KEY_RAW" > key.p8
          chmod 600 key.p8

      - name: Test Snowflake connection (FORCED PARAMS)
        run: |
          snow connection test \
            --account "$SNOWFLAKE_ACCOUNT" \
            --user "$SNOWFLAKE_USER" \
            --role "$SNOWFLAKE_ROLE" \
            --warehouse "$SNOWFLAKE_WAREHOUSE" \
            --database "$SNOWFLAKE_DATABASE" \
            --authenticator SNOWFLAKE_JWT \
            --private-key-path key.p8 \
            --debug

      - name: Deploy SQL
        run: |
          FILES=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" | grep '^Snowflake/.*\.sql$' || true)

          if [ -z "$FILES" ]; then
            echo "No SQL changes"
            exit 0
          fi

          echo "SQL files to run:"
          echo "$FILES"

          FILES_SORTED=$(echo "$FILES" | sort)

          while IFS= read -r file; do
            [ -z "$file" ] && continue
            echo "Running $file"
            snow sql \
              --account "$SNOWFLAKE_ACCOUNT" \
              --user "$SNOWFLAKE_USER" \
              --role "$SNOWFLAKE_ROLE" \
              --warehouse "$SNOWFLAKE_WAREHOUSE" \
              --database "$SNOWFLAKE_DATABASE" \
              --authenticator SNOWFLAKE_JWT \
              --private-key-path key.p8 \
              -f "$file"
          done <<< "$FILES_SORTED"
